apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deploy.yaml
  - ./svc.yaml
namePrefix: keda-celery-flower-scaler-
commonLabels:
  app.kubernetes.io/name: "keda-celery-flower-scaler"
  app.kubernetes.io/instance: "keda-celery-flower-scaler"
  app.kubernetes.io/version: "0.1.0"
images:
  - name: keda-celery-flower-scaler
    newName: ghcr.io/lcogt/keda-celery-flower-scaler
